[project]
name = "nanojax"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=4.4.1",
    "jax[cuda12]",
    "maturin>=1.9.6",
    "pyarrow>=22.0.0",
    "tiktoken>=0.12.0",
    "zarr>=3.1.3",
]

[project.optional-dependencies]
metal = ["jax-metal>=0.1.1"]
cpu = ["jax"]

[tool.uv]
conflicts = [
    [
        { package = "jax" },
        { extra = "metal" },
    ],
    [
        { package = "jax" },
        { extra = "cpu" },
    ],
]

[build-system]
requires = ["maturin>=1.7,<2.0"]
build-backend = "maturin"


[tool.maturin]
module-name = "rustbpe"
bindings = "pyo3"
python-source = "."
manifest-path = "rustbpe/Cargo.toml"

